accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup', views.signup, name='signup'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path, include
from products  import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, include
from . import views

app_name = 'products'

urlpatterns = [
    path('create', views.create, name='create'),
    path('<int:product_id>/', views.detail, name='detail'),
    path('<int:product_id>/upvote', views.upvote, name='upvote'),
]

accounts/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Product(models.Model):
    title = models.CharField(max_length=220)
    url = models.TextField()
    pub_date = models.DateTimeField()
    votes_total = models.IntegerField(default=1)
    image = models.ImageField(upload_to='images/')
    icon = models.ImageField(upload_to='images/')
    body = models.TextField()

    hunter = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:100]

    def pub_date_pretty(self):
        return self.pub_date.strftime("%b %e %Y")

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def signup(request):
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            try:
                user = User.objects.get(username=request.POST["username"])
                return render(request, 'accounts/signup.html',
                          {'error': 'Username has been already taken!'})
        
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST["username"], password=request.POST["password1"])
                auth.login(request, user)
                return redirect('home')

        else:
            return render(request, 'accounts/signup.html',
                          {'error': 'Password Does Not Allowed!'})
                
    
    else:
        return render(request, 'accounts/signup.html')


def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'accounts/login.html',
                          {'error': 'Account Invalid!'})
 
    else:        
        return render(request, 'accounts/login.html')


def logout(request):
    if request.method == "POST":
        auth.logout(request)

        return redirect('accounts:login')

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Product
from django.utils import timezone

def home(request):
    products = Product.objects.all()
    return render(request, 'products/home.html', {'products': products})


@login_required(login_url="/accounts/signup")
def create(request):
    if request.method == "POST":
        if request.POST["title"] and request.POST["body"] and request.FILES["image"] and request.FILES["icon"] and request.POST["url"]:
            product = Product()
            product.title = request.POST["title"]
            product.body = request.POST["body"]
            if request.POST["url"].startswith('http'):
                
                product.url = request.POST["url"]

            else:
                product.url = 'http://' + request.POST["url"]

            product.icon = request.FILES["icon"]
            product.image = request.FILES["image"]
            product.pub_date = timezone.datetime.now()
            product.hunter = request.user
            product.save()

            return redirect('/products/' + str(product.id))
        
    else:
        return render(request, 'products/create.html')


def detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'products/detail.html', {'product': product})

@login_required(login_url="/accounts/signup")
def upvote(request, product_id):
    if request.method == "POST":
        product = get_object_or_404(Product, pk=product_id)
        product.votes_total += 1
        product.save()

        return redirect('/products/' + str(product.id))
    
    

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h3> Login Page  </h3>

{% if error %}
<strong style="color:red;">{{error}}</strong>
{% endif %}

<form method="post" action="{% url 'accounts:login' %}" style="max-width: 500px;">
  {% csrf_token %}
  <p>  Username: </p>
  <input type="text" name="username" class="form-control"/>

  <p> Password: </p>
  <input class="form-control" type="password" name="password" />

  <p> &copy; </p>
  <input class="btn btn-primary" type="submit" value="Login" />
  
</form>


{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}

<h3> Sign UP Page  </h3>

{% if error %}
<strong style="color:red;">{{error}}</strong>
{% endif %}

<form method="post" action="{% url 'accounts:signup' %}" style="max-width: 500px;">
  {% csrf_token %}
  <p>  Username: </p>
  <input type="text" name="username" class="form-control"/>

  <p> Password: </p>
  <input class="form-control" type="password" name="password1" />

  <p> Confirm  Password: </p>
  <input class="form-control" type="password" name="password2" />

  <p> &copy; </p>
  <input class="btn btn-primary" type="submit" value="Sing Up" />
  
</form>


{% endblock %}

products/templates/products/create.html
{% extends 'base.html' %}

{% block content %}

<h3> Sign UP Page  </h3>

{% if error %}
<strong style="color:red;">{{error}}</strong>
{% endif %}

<form method="post" action="{% url 'products:create' %}" style="max-width: 500px;" enctype="multipart/form-data">
  {% csrf_token %}
  <p>  Title: </p>
  <input type="text" name="title" class="form-control"/>

  <p> Body: </p>
  <input class="form-control" type="text" name="body" />

  <p> URL: </p>
  <input class="form-control" type="text" name="url" />

  
  <p> Icon: </p>
  <input class="form-control" type="file" name="icon" />

    <p> Image: </p>
  <input class="form-control" type="file" name="image" />


  <p> &copy; </p>
  <input class="btn btn-primary" type="submit" value="Add Product" />
  
</form>


{% endblock %}

products/templates/products/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-2">
    <img src="{{product.image.url}}" class="img-fluid"/>
  </div>


  <div class="col-10">
    <a href="{{ product.url }}"><h1> {{product.title}} </h1> </a>
  </div>
  
</div>
<div class="row mt-3">
  <div class="col-8">
    <img src="{{ product.image.url }}" class="img-fluid">
  </div>

  <div class="col-4">
    <a href="javascript:{document.getElementById('upvote').submit()}" ><button class="btn btn-success btn-lg btn-block"> Upvote {{product.votes_total}} </button> </a>
  </div>
  
</div>

<div class="row mt-1">
  <div class="col-4">
    <h4> Hunted by {{ product.hunter.username }} </h4>
  </div>
  <div class="col-4 text-right">
    <small> {{ product.pub_date_pretty}} </small>
  </div>
  
</div>

<div class="row">
  <div class="col-8">
    <p> {{ product.body }} </p>
  </div>
  <div class="col-4">
    <form id="upvote" action="{% url 'products:upvote' product.id %}" method="post">
      {% csrf_token %}
      <input type="hidden">
    </form>
    
  </div>
</div>

{% endblock %}

products/templates/products/home.html
{% extends 'base.html' %}

{% block content %}

<h3> Home Page </h3>

{% for product in products %}

<div class="row mt-3">
  <div class="col-2" onclick="window.location='{% url 'products:detail' product.id %}'">
    <img src="{{ product.image.url }}" class="img-fluid"/>
  </div>
  <div class="col-6">
    
      <h3> {{ product.title }} </h3>
    
    
    <p> {{ product.summary }} </p>
  </div>
  <div class="col-4">
    <a href="javascript:{document.getElementById('upvote{{product.id}}').submit()}" class="btn btn-block btn-success btn-md"> Upvote {{ product.votes_total }} </a>
    <form id="upvote{{product.id}}" action="{% url 'products:upvote' product.id %}" method="post">
      {% csrf_token %}
      <input type="hidden">
    </form>
    
  </div>
  
</div>


{% endfor %}

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="For Product Hunt">
    <meta name="author" content="Prime Lazier">

    <title>Product Hunt</title>

    <!-- Bootstrap core CSS -->
    {% load static %}
    <link rel='icon' type='favicon' href='{% static 'letter-a.png' %}' />
<link href="/media/css/bootstrap.min.css" rel="stylesheet">

<meta name="theme-color" content="#563d7c">


    <!-- Custom styles for this template -->
    <link href="/media/css/album.css" rel="stylesheet">
  </head>
  <body>
    <header>
     {% include 'nav.html' %}
        
</header>

<main class="container" role="main">
  {% block content %}

  {% endblock %}
</main>

<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <p>This is my personal blog and web page. Not deal to the others</p>
    <p class="text-center"> &copy; Prime Lazier {% now 'Y' %} </p>
  </div>
</footer>
<script src="/media/js/jquery.slim.min.js" type='text/javascript'></script>
<script src="/media/js/bootstrap.min.js" type='text/javascript'> </script>

  </body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container">
	<a class="navbar-brand" href="{% url 'home' %}">
	   <img src="{% static 'letter-a.png' %}" width=35 height=auto>
	    <strong> Prime Lazier</strong>
	</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav ml-auto">
      <a class="nav-item nav-link active" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
      {% if user.is_authenticated %}
      <a class="nav-item nav-link" href="{% url 'products:create' %}"><span class="oi oi-plus"></span>Create </a>
      <a class="nav-item nav-link" href="javascript:{document.getElementById('logout').submit()}">Logout</a>
      <form id="logout" method="POST" action="{% url 'accounts:logout' %}" >
	{% csrf_token %}
	<input type="hidden" />
      </form>
      
      {% else %}
      <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
      <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
      {% endif %}
    </div>
  </div> 
  </div>
</nav>